name: mytasks
description: A Simple Tasks App.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

 
  assets:
    - assets/img/
 
  fonts:
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: Acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Bold.ttf
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
 
